import {
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLeetcode,
  IconBrandLinkedin,
  // IconBrandYoutube,
} from "@tabler/icons-react";
const Info = {
  name: "Nikhil Belgaonkar",
  stack: [
    "Software Engineer",
    "Full stack Web Developer",
    "Competitive Programmer",
  ],
  bio: "I'm a Passionate software engineer with strong background in programming and web development.I specialized in crafting efficent and scalable solutions, deliver top-notch web applications that exceeds clients expectations.Let's connect and create amazing together!",
};
const ProjectInfo = [
  // {
  //   title: "Ekart E-comm App",
  //   desc: "Ekart is a modern, fully responsive e-commerce platform built using React, TailwindCSS, Heroicons, and HeadlessUI, offering a seamless shopping experience across all devices. It features secure user authentication with login, registration, and logout functionalities. Users can add items to a wishlist or remove them, search for specific products, and add them to a shopping cart for purchase. The checkout process includes form validation for address and payment information, ensuring accuracy and security. After purchase, users can view their order history in the Orders section. Ekart combines robust functionality with a sleek, intuitive design, making online shopping effortless and enjoyable.",
  //   image: "Ekart.png",
  //   live: true,
  //   technologies: ["React", "Tailwind", "Redux", "Heroicons", "HeadlessUI"],
  //   link: "https://code-mars.github.io/Ekart/",
  //   github: "https://github.com/Code-Mars/Ekart/",
  // },
  {
  title: "Expense Splitter API",
  desc: "Expense Splitter is a scalable, RESTful API built with Spring Boot that helps users easily split group expenses. It supports group and user management, expense tracking, balance calculation, and smart debt resolution. The backend features secure role-based access, JWT authentication, and efficient relational data modeling with JPA. Advanced features include pagination, filtering, meaningful error handling, and Swagger API documentation. Designed with real-world use in mind, this project follows clean code, modular structure, and is future-ready for frontend integration or microservices architecture.",
  image: "expense-splitter-api.png", // placeholder name; update as needed
  live: false,
  technologies: ["Java", "Spring Boot", "JPA", "MySQL", "JWT", "Swagger", "Postman"],
  link: "", // Leave empty if not deployed
  github: "https://github.com/NikhilN10/Expense_Spitter_API/tree/master", // replace with actual repo
},

  // {
  //   title: "Facebook Clone",
  //   desc: "Facebook Clone is a full-stack web application that replicates the core features of Facebook, including user authentication, posting, and commenting. The front end is built with React, TailwinCSS, Tabler-Icons, Mantine and Firebase, while the back end uses Firebase for user authentication and data storage. Users can create an account, log in, post updates, and comment on posts. The app features real-time updates, so users can see new comments as they are posted. Facebook Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
  //   image: "Facebook.png",
  //   live: false,
  //   technologies: [
  //     "React",
  //     "Springboot",
  //     "MongoDB",
  //     "Tailwind",
  //     "Tabler-Icons",
  //     "Firebase",
  //   ],
  //   link: "https://github.com/Code-Mars/Facebook-Clone",
  //   github: "https://github.com/Code-Mars/Facebook-Clone",
  // },
  // {
  //   title: "Spotify Clone",
  //   desc: "Spotify Clone is a full-stack web application that replicates the core features of Spotify, including user authentication, music playback, and playlist creation. The front end is built with React, TailwindCSS, Heroicons, and Firebase, while the back end uses Firebase for user authentication and data storage. Users can create an account, log in, search for songs, and create playlists. The app features real-time updates, so users can see new songs as they are added. Spotify Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
  //   image: "Spotify.png",
  //   live: false,
  //   technologies: [
  //     "React",
  //     "Springboot",
  //     "Tailwind",
  //     "Tabler-Icons",
  //     "MongoDB",
  //     "Firebase",
  //   ],
  //   link: "https://github.com/Code-Mars/Spotify-Clone",
  //   github: "https://github.com/Code-Mars/Spotify-Clone",
  // },
  // {
  //   title: "Travel Tracker",
  //   desc: "Travel Tracker is a full-stack web application that allows users to track their travel experiences and share them with others. The front end is built with React, Bootstrap, while the back end uses Node.js, Express, and PostgresSQL. Users can create an account, log in, add new trips, and view their past trips on a map. The app features a clean, modern design with interactive maps and a user-friendly interface. Travel Tracker combines functionality with style, making it easy and enjoyable to record and share travel memories.",
  //   image: "Travel.png",
  //   live: false,
  //   technologies: ["React", "Node.js", "PostgresSQL", "Express", "Bootstrap"],
  //   link: "https://github.com/Code-Mars/Travel-Tracker",
  //   github: "https://github.com/Code-Mars/Travel-Tracker",
  // },
  // {
  //   title: "Instagram Clone",
  //   desc: "Instagram Clone is a full-stack web application that replicates the core features of Instagram, including user authentication, image uploading, and commenting. The front end is built with React, TailwindCSS, and Heroicons, while the back end uses Firebase for user authentication and image storage. Users can create an account, log in, upload images, and comment on posts. The app features real-time updates, so users can see new comments as they are posted. Instagram Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
  //   image: "Instagram.png",
  //   live: false,
  //   technologies: [
  //     "React",
  //     "Springboot",
  //     "Tailwind",
  //     "Heroicons",
  //     "Firebase",
  //     "MongoDB",
  //   ],
  //   link: "https://github.com/Code-Mars/Instagram-Clone",
  //   github: "https://github.com/Code-Mars/Instagram-Clone",
  // },
  {
    title: "Finshark",
    desc: "FinShark helps investors find relavent financial documents without the noise of short-term data.FinShark is a web application designed for financial data management, enabling users to analyze stocks, manage portfolios, and interact with financial data through a user-friendly interface. The application consists of a backend API built with C# and ASP.NET, and a frontend developed using React, providing a seamless experience for users to access and manage their financial information",
    image: "Finshark.png",
    live: false,
    technologies: ["C#", ".Net", "React", "TypeScript", "CSS", "MySql"],
    link: "https://github.com/NikhilN10/Finshark",
    github: "https://github.com/NikhilN10/Finshark",
  },
];

const SkillInfo = [
  {
    title: "Frontend",
    skills: [
      "HTML",
      "CSS",
      // "SASS",
      "JavaScript",
      "React JS",
      //"Angular",
      "Redux",
      "Tailwind CSS",
      //  "GSAP",
      "Material UI",
      "Bootstrap",
    ],
  },
  {
    title: "Backend",
    skills: [
      "Springboot",
      "Spring Security",
      "Hibernate",
      "NetCore",
      "Rest API",
      "Node JS",
      "Express JS",
      "MySQL",
      "MongoDB",
      "Firebase",
      "PostgresSQL",
    ],
  },
  {
    title: "Languages",
    skills: ["C", "C++", "Java", "JavaScript", "TypeScript", "C_Sharp"],
  },
  {
    title: "Tools",
    skills: [
      "Git",
      "Github",
      "VS Code",
      "Postman",
      "Docker",
      "MongoDB Compass",
      "Spring Tool Suite",
    ],
  },
];
const socialLinks = [
  { link: "https://github.com/NikhilN10", icon: IconBrandGithub },
  {
    link: "https://www.linkedin.com/in/nikhil-belgaonkar/",
    icon: IconBrandLinkedin,
  },
  { link: "https://leetcode.com/u/NikhilN10/", icon: IconBrandLeetcode },
  {
     link: "https://www.instagram.com/itz_nicky_nix/",
    icon: IconBrandInstagram,
  },
];

const ExperienceInfo = [
  {
    role: "Software Engineer",
    company: "Encora",
    date: "June 2024 - Present",
    desc: "I am a Software Engineer with 1 year of experience in leading full-stack development using Spring Boot, React. I have built scalable microservices and intuitive user interfaces, optimized system performance through seamless integration of frontend and backend components, and improved application security by implementing secure RESTful APIs. Working in agile teams, I contributed to innovative and efficient solutions that ensured high-quality software delivery.",
    skills: [
      "Java",
      "Springboot",
      "React JS",
      "Rest API",
      "Node JS",
      "MySQL",
      "AWS",
      "Docker",
      "Git",
      "Microservices",
    ],
  },
  // {
  //   role: "System Engineer",
  //   company: "Encora",
  //   date: "Nov 2022 - Sep 2023",
  //   desc: " I leveraged my skills in Java, Selenium, automation testing, and MySQL to design and implement automated testing frameworks, ensuring robust software validation. I optimized database performance and reliability, and collaborated with cross-functional teams to enhance system operations and ensure seamless integration.",
  //   skills: [
  //     "Java",
  //     "MySQL",
  //     "Hibernate",
  //     "Selenium",
  //     "Jenkins",
  //     "JIRA",
  //     "Automation Testing",
  //   ],
  // },
];
const Slugs = [
  "typescript",
  "spring",
  "javascript",
  "dart",
  "java",
  "react",
  "angular",
  "flutter",
  "android",
  "html5",
  "css3",
  "springboot",
  "mongodb",
  "selenium",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "mysql",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "testinglibrary",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "androidstudio",
  "sonarqube",
  "figma",
];
export { Info, ProjectInfo, socialLinks, SkillInfo, ExperienceInfo, Slugs };
